### ISSUE TITLE
PHP Fatal error:  Call to undefined function dl()

### ISSUE THREAD

**Issue by aaronrenner** [rothkj1022/phppickem#13]
I don't do much php, so I'm sorry if this is an easy fix. I was able to run through the installer without any issues, but I'm getting the following error (in /var/log/apache2/error.log) when visiting login.php.

```
PHP Fatal error:  Call to undefined function dl() in /home/phppickem/phppickem/includes/classes/crypto.php on line 31
```

I'm on Ubuntu 14.04 and running PHP Version 5.5.9-1ubuntu4.11. Please let me know what other pertinent info you might need, and any suggestions on getting this running would be appreciated.

**Comment by rothkj1022** [comment]
It sounds like you may not have mcrypt installed or configured properly.  You'll need to have mcrypt enabled in your php environment.

Thank you for bringing this to my attention, though, as I will remove the lines of code that tries to load mcrypt if it is not already found.  Apparently the dl function has been removed since php 5.3 for security reasons.

**Comment by joshbarraza** [comment]
Unsubscribe

**Comment by aaronrenner** [comment]
Thanks @rothkj1022. I pulled down your latest code and it did turn out to be an mcrypt issue. I enabled mcrpyt and everything is working now.
